In [ ]:
import numpy
def arrays(arr, arr1, arr2):
    arr = numpy.array(arr, dtype = int)
    arr1 = numpy.array([arr1], dtype = int)
    arr2 = numpy.array([arr2], dtype = int)

    add = numpy.add(arr1,arr2)
    sub = numpy.subtract(arr1, arr2)
    mul = numpy.multiply(arr1, arr2)
    div = numpy.floor_divide(arr1, arr2)
    mod = numpy.mod(arr1, arr2)
    power = numpy.power(arr1, arr2)
    return add,sub,mul,div,mod,power

arr = input().strip().split(' ')

arr1 = input().strip().split(' ')
arr2 = input().strip().split(' ')
add,sub,mul,div,mod,power = arrays(arr, arr1, arr2)
print(add)
print(sub)
print(mul)
print(div)''
print(mod)
print(power)

1 2 3 
4 5 6
7 8 9
[[11 13 15]]
[[-3 -3 -3]]
[[28 40 54]]
[[0 0 0]]
[[4 5 6]]
[[   16384   390625 10077696]]


In [ ]:

import numpy
N, M = map(int, input().split())

A = numpy.array([input().split() for i in range(N)],dtype = int)
print(numpy.max(numpy.min(A, axis=1), axis=0))

1 2
3 4
3


In [ ]:
aa='abcdef'
print(aa[::-1])

fedcba


In [ ]:
import math
n=5
a=math.factorial(n)
print(a)

120


In [ ]:
def factorial(n):
    return 1 if (n==0 or n==1) else n*factorial(n-1)
num=int(input("enter the number for to find the factorial: "))
print('Factorial is: ',factorial(num))

enter the number for to find the factorial: 5
Factorial is:  120


In [ ]:
a=9
if a%2:
    print('its prime')
else:
    print('not prime')

its prime


In [ ]:
num=8
if num>1:
    for i in range(2,int(num/2)+1):
        if (num%i)==0:
            print(num, 'is not prime number')
            break
    else:
        print(num,'is a prime number')
else:
    print(num, 'is not prime number')

8 is not prime number


In [ ]:
(int(11/2)+1)
11%6


5

In [ ]:
a='computer'
index=len(a)
for i in a:
    print(a[0:index])
    index -=1

computer
compute
comput
compu
comp
com
co
c


In [ ]:
#nested loop
i=1
while(i<=6):
    for j in range(1,i):
        print(j,end='\t')
    print(end='\n')
    i+=1


1	
1	2	
1	2	3	
1	2	3	4	
1	2	3	4	5	


In [ ]:
i=1
while(i<=6):
    print(i,end='\t')
    i+=1

1	2	3	4	5	6	

In [ ]:
for j in range(1,2):
    print(j, end='\t')


1	

In [ ]:
for i in range(1,6):
    print(i,end='\t')

1	2	3	4	5	

In [ ]:
def hello():
    print('hello python')

print(hello())

hello python
None


In [ ]:
import math
print(math.floor(26.7))
print(math.ceil(26.3))

26
27


In [ ]:
print(abs(-25+12.0))
print(abs(-3.2))

13.0
3.2


In [ ]:
print(ord('$'))#to give the unicode character inverse of chr()
print(chr(36))# to give ascii value from unicode inverse of ord()


36
$



In [ ]:
round(18.2,3)
print(round(0.5100,3))

0.51


In [ ]:
print(format(33,'x'))
print(format(0b110,'d'))

21
6


In [ ]:
str1=input('enter a string: ')
index=-1
while index>=-(len(str1)):
    print(str1[index])
    index+=-1

enter a string: priya
a
y
i
r
p


In [ ]:
#palindrome
str1=input("Enter a string: ")
str2=str1[::-1]
print(str2)
if str2==str1:
    print('palindrome')
else:
    print("not polindrome")

Enter a string: malayalam
malayalam
palindrome


In [ ]:
patt='*'
i=1
while i<=5:
    print(patt *i)
    i+=1

*
**
***
****
*****


In [ ]:
strr=input('enter a string: ')
str2='aAeEiIoOuU'
v,c=0,0
for i in strr:
    if i in str2:
        v+=1
    else:
        c+=1
print('string contain {} constraints and vowels {}'.format(v,c))


enter a string: python is interpreted language
string contain 10 constraints and vowels 20


In [ ]:
#abecedarian seriesa
aa='ABCDEFGHI'
bb='ate'
for i in aa:
    print(i+bb, end='\t')

Aate	Bate	Cate	Date	Eate	Fate	Gate	Hate	Iate	

In [ ]:
def count(s,c):
    c1=0
    for i in s:

        if i==c:
            c1+=1
    return c1
str1=input('enter a string: ')
chh=input('enter a charater to search: ')
cnt=count(str1,chh)
print("The given charcter {} is occures {} times in the given string".format(chh,cnt))

enter a string: data science
enter a charater to search: a
The given charcter a is occures 2 times in the given string


In [ ]:
#pg 148
#to print numbers divisible %4
divby=[]
for i in range(20):
    if(i%4==0):
        divby.append(i)
print(divby)

[0, 4, 8, 12, 16]


In [ ]:
#check whether a country is member of BRICS or not
country=['India','Russia','Srilanka','China','Brazil']
is_member=input('Enter the name of country: ').capitalize()
if is_member in country:
    print(is_member,'is the member of BRICS')
else:
    print(is_member,'is not a member of BRICS')


Enter the name of country: jordan
Jordan is not a member of BRICS


In [ ]:
#print the marks and show the total marks
marks=[]
sub=['tamil','eng','mat','sci','s.sci']
for i in range(5):
    m=int(input('Enter mark= '))
    marks.append(m)
for j in range(len(marks)):
    print("{}.{} mark ={}".format(j+1,sub[j],marks[j]))
    #print(f"{i}. {sub[i]} mark = {marks[i]}")
print('total marks=',sum(marks))

Enter mark= 67
Enter mark= 73
Enter mark= 84
Enter mark= 85
Enter mark= 55
1.tamil mark =67
2.eng mark =73
3.mat mark =84
4.sci mark =85
5.s.sci mark =55
total marks= 364


In [ ]:
#display sum of all prices and product of all the prices and find avg

items=[]
prod=1

for i in range(5):
    print('enter price for item {} :'.format(i+1))
    p=int(input())
    items.append(p)
for j in range(len(items)):
    print('price for item {}= Rs.{}'.format(j+1,items[j]))
    prod=prod*items[i]
print('sum of all prices Rs:',sum(items))
#rint('product of all price Rs:',prod)
print('avg all price Rs:',sum(items)/len(items))

enter price for item 1 :
1
enter price for item 2 :
54
enter price for item 3 :
64
enter price for item 4 :
34
enter price for item 5 :
34
price for item 1= Rs.1
price for item 2= Rs.54
price for item 3= Rs.64
price for item 4= Rs.34
price for item 5= Rs.34
sum of all prices Rs: 187
avg all price Rs: 37.4


In [ ]:
#the fibonacci series and store it in a list.then find the sum of values
#....................................
a=-4
b=4
n=int(input('enter no.of terms: '))
i=0
sum=0
fibo=[]
while i<n:
    s=a+b
    fibo.append(s)
    sum+=s
    a=b
    b=s
    i+=1
print('Fibnacci series upto '+ str(n) +' terms is:'+str(fibo))
print('The sum of Fibonacci series: ',sum)

enter no.of terms: 6
Fibnacci series upto 6 terms is:[0, 4, 4, 8, 12, 20]
The sum of Fibonacci series:  48


In [ ]:
#a list of possitive and negative number. create a new tuple that has only positive numbers from the list


numbers=(5,-8,6,8,-4,3,1)
positive=()

for i in numbers:
    if i>0:
        positive+=(i,)
print('positive numbers: ',positive)

positive numbers:  (5, 6, 8, 3, 1)


In [ ]:
#prime numbers
num = 2
# If given number is greater than 1
if num > 1:
	# Iterate from 2 to n / 2
	for i in range(2, int(num/2)+1):
		# If num is divisible by any number between
		# 2 and n / 2, it is not prime
		if (num % i) == 0:
			print(num, "is not a prime number")
			break
	else:
		print(num, "is a prime number")
else:
	print(num, "is not a prime number")


2 is a prime number


In [ ]:
num=3
if num>1:
    for i in range(2,int(num/2)+1):
        if(num%i)==0:
            print(num,"is not prime number")
            break
    else:
        print(num,'is a prime number')
else:
    print(num,'is not prime number')

3 is a prime number


In [ ]:
int(3/2)+1

2

In [ ]:
name = "priya"
output = "*".join(name)
print(output)

p*r*i*y*a


In [ ]:
name = "priya"
output = ",".join(name)
print(output)

p,r,i,y,a


In [ ]:
n = 10
num1 = 0
num2 = 1
next_number = num2
count = 1

while count <= n:
	print(next_number, end=" ")
	count += 1
	num1, num2 = num2, next_number
	next_number = num1 + num2
print()


1 2 3 5 8 13 21 34 55 89 


In [ ]:
#fiboncci

n=8
n1=0
n2=1
next_number=n2
count=1
while count<=n:
    print(next_number,end=" ")

    n1,n2=n2,next_number
    #print(n1,n2)
    next_number=n1+n2
    print(end=' ')
    count+=1




1  2  3  5  8  13  21  34  

In [ ]:
# python 3 program
# to check whether the given number is armstrong or not
# without using power function

n = 153 # or n=int(input()) -> taking input from user
s = n # assigning input value to the s variable
b = len(str(n))
sum1 = 0
while n != 0:
	r = n % 10
	sum1 = sum1+(r**b)
	n = n//10
if s == sum1:
	print("The given number", s, "is armstrong number")
else:
	print("The given number", s, "is not armstrong number")


The given number 153 is armstrong number


In [ ]:
n=int(input('enter the number: '))
s=n
v=len(str(n))
d1=0

while n!=0:
    r=n%10#remainder,the last digit of n....(3)
    d1=d1+(r**v)
    n=n//10 #is updated by removing the last digit (using integer division //)...(15)
if s==d1:
    print('the given number',s,'is armstrong')
else:
    print('not armstrong',s)

enter the number: 153
the given number 153 is armstrong


In [ ]:
n = 153 # or n=int(input()) -> taking input from user
s = n # assigning input value to the s variable
b = len(str(n))
b

3

In [ ]:
153//10

15

In [ ]:
153%10


3

In [ ]:
3**3

27

In [ ]:
q=11
if q>1:
    for i in range(2,int(q/2)+1):
        if q%i==0:
            print(q,'not prime num')
            break
    else:
        print(q, 'prime num')
else:
    print(q,'not prime num')

11 prime num


In [ ]:
n=int(input('enter no; '))
n1=0
n2=1
nn=n2
count=1
while count<=7:
    print(nn, end='')
    n1,n2=n2,nn
    nn=n1+n2
    print(end=' ')
    count+=1

enter no; 6
1 2 3 5 8 13 21 